//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DM.UBP.PBIRS.Security {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DM.UBP.PBIRS.Security.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 增加账号时发生错误。 的本地化字符串。
        /// </summary>
        internal static string AddAccountError {
            get {
                return ResourceManager.GetString("AddAccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有找到\&quot;AdminConfiguration\&quot;配置信息 的本地化字符串。
        /// </summary>
        internal static string AdminConfiguration {
            get {
                return ResourceManager.GetString("AdminConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名或密码错误。 的本地化字符串。
        /// </summary>
        internal static string InvalidUsernamePassword {
            get {
                return ResourceManager.GetString("InvalidUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Url reservation found for the \&quot;ReportServerWebService\&quot; application. 的本地化字符串。
        /// </summary>
        internal static string MissingUrlReservation {
            get {
                return ResourceManager.GetString("MissingUrlReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number of operation names don&apos;t match. 的本地化字符串。
        /// </summary>
        internal static string OperationNameError {
            get {
                return ResourceManager.GetString("OperationNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred while attempting to get the ReportServer Url.  的本地化字符串。
        /// </summary>
        internal static string RSUrlError {
            get {
                return ResourceManager.GetString("RSUrlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unrecognized configuration element. 的本地化字符串。
        /// </summary>
        internal static string UnrecognizedElement {
            get {
                return ResourceManager.GetString("UnrecognizedElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户已注册 的本地化字符串。
        /// </summary>
        internal static string UserRegistered {
            get {
                return ResourceManager.GetString("UserRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户验证错误 的本地化字符串。
        /// </summary>
        internal static string VerifyError {
            get {
                return ResourceManager.GetString("VerifyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户验证时发生异常 的本地化字符串。
        /// </summary>
        internal static string VerifyUserException {
            get {
                return ResourceManager.GetString("VerifyUserException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有发现WMI类 的本地化字符串。
        /// </summary>
        internal static string WMIClassError {
            get {
                return ResourceManager.GetString("WMIClassError", resourceCulture);
            }
        }
    }
}
