// <auto-generated />
namespace DM.UBP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update_ABP_Migrations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_ABP_Migrations));
        
        string IMigrationMetadata.Id
        {
            get { return "201706200346086_Update_ABP_Migrations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
